//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yoneticim
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Gorevli
    {
        public Gorevli()
        {
            this.Kalemler = new List<Kalem>();
        }

        [Key]
        public int Id { get; set; }

        [Required, DisplayName("Adı")]
        public string Adi { get; set; }

        [Required, DisplayName("Soyadı")]
        public string Soyadi { get; set; }

        [DisplayName("İş Tanımı")]
        public string IsTanimi { get; set; }

        [DisplayName("Maaşı"), DataType(DataType.Currency)]
        public Nullable<decimal> Maasi { get; set; }

        [Required, DisplayName("TC No")]
        public string TcNo { get; set; }

        [Required, DisplayName("Sigorta No")]
        public string SigortaNo { get; set; }

        public int MulkId { get; set; }

        [DisplayName("Görevli Türü")]
        public int GorevliTurleriId { get; set; }

        public virtual GorevliTuru GorevliTurleri { get; set; }
        public virtual Mulk Mulkler { get; set; }
        public virtual ICollection<Kalem> Kalemler { get; set; }
    }
}
