//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yoneticim
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GorevliTuru
    {
        public GorevliTuru()
        {
            this.Gorevliler = new List<Gorevli>();
        }

        [Key]
        public int Id { get; set; }
        public string Adi { get; set; }

        public virtual ICollection<Gorevli> Gorevliler { get; set; }
    }
}
