//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yoneticim
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kalem
    {
        [Key]
        public int Id { get; set; }
        public int MulkId { get; set; }
        public bool GelirMi { get; set; }
        public decimal Tutar { get; set; }
        public string Açıklama { get; set; }
        public int Yıl { get; set; }
        public int Ay { get; set; }
        public Nullable<int> GorevliId { get; set; }
        public bool AidatMi { get; set; }
        public Nullable<int> DaireId { get; set; }

        public virtual Daire Daireler { get; set; }
        public virtual Gorevli Gorevliler { get; set; }
        public virtual Mulk Mulkler { get; set; }
    }
}
