//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yoneticim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daireler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Daireler()
        {
            this.Kalemlers = new HashSet<Kalemler>();
        }
    
        public int Id { get; set; }
        public int No { get; set; }
        public Nullable<byte> Kat { get; set; }
        public string SahibiAdi { get; set; }
        public string SahibiSoyadi { get; set; }
        public string SahibiTel { get; set; }
        public string KiraciAdi { get; set; }
        public string KiraciSoyadi { get; set; }
        public string KiraciTel { get; set; }
        public int MulkId { get; set; }
        public string EPosta { get; set; }
        public string Sifre { get; set; }
    
        public virtual Mulkler Mulkler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kalemler> Kalemlers { get; set; }
    }
}
