//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yoneticim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mulkler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mulkler()
        {
            this.Dairelers = new HashSet<Daireler>();
            this.Gorevlilers = new HashSet<Gorevliler>();
            this.Kalemlers = new HashSet<Kalemler>();
            this.Mulkler1 = new HashSet<Mulkler>();
        }
    
        public int Id { get; set; }
        public string Adres { get; set; }
        public string Adi { get; set; }
        public Nullable<int> MulkId { get; set; }
        public int BlokSayisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daireler> Dairelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gorevliler> Gorevlilers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kalemler> Kalemlers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mulkler> Mulkler1 { get; set; }
        public virtual Mulkler Mulkler2 { get; set; }
    }
}
