//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yoneticim
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YoneticimDBEntities : DbContext
    {
        public YoneticimDBEntities()
            : base("name=YoneticimDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Daireler> Dairelers { get; set; }
        public virtual DbSet<Gorevliler> Gorevlilers { get; set; }
        public virtual DbSet<GorevliTurleri> GorevliTurleris { get; set; }
        public virtual DbSet<Kalemler> Kalemlers { get; set; }
        public virtual DbSet<Mulkler> Mulklers { get; set; }
        public virtual DbSet<Yoneticiler> Yoneticilers { get; set; }
    }
}
